from .vehicles.create_vehicle import CreateVehicleUsecase
from .vehicles.list_vehicles import ListVehicleUsecase
from .vehicles.consult_vehicles import ConsultVehicleByIdUsecase
from .vehicles.update_vehicle import UpdateVehicleUsecase
from .demands.consult_demand import ConsultDemandUsecase
from .demands.list_demands import ListDemandsUsecase
from .demands.update_demand import UpdateDemandUsecase
from .demands.create_demand import CreateDemandUsecase
from .places.consult_place import ConsultPlaceUsecase
from .places.list_places import ListPlacesUsecase
from .places.create_place import CreatePlaceUsecase
from .places.update_place import UpdatePlaceUsecase
